#!/usr/bin/env bash
# Regenerate tests/corpus/baselines.csv from the current detector. Run after an
# INTENTIONAL change to detect_component (e.g. a refine step, a new branch, a
# threshold tweak that's been reviewed): the smoke gate fails on any per-frame
# (cx, cy, w, h, angle) drift > tolerance, so the baseline must be re-pinned
# explicitly when the output legitimately moves.
#
#   tools/regen_baselines.sh                                 # default corpus
#   tools/regen_baselines.sh tests/corpus                    # explicit
#
# Writes to stdout AND tests/corpus/baselines.csv. Smoke reads the file.
set -uo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd)
CORPUS_ROOT="${1:-$REPO/tests/corpus}"
TUNE="$REPO/build-host/mvision-tune"

if [ ! -x "$TUNE" ]; then
    echo "$0: build $TUNE first (cmake --build build-host)" >&2
    exit 1
fi
if [ ! -d "$CORPUS_ROOT" ]; then
    echo "$0: $CORPUS_ROOT is not a directory" >&2
    exit 1
fi

OUT="$REPO/tests/corpus/baselines.csv"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
    echo "# CompResult regression baseline -- auto-generated by tools/regen_baselines.sh."
    echo "# Regenerate after an INTENTIONAL detector change that moves the per-frame"
    echo "# (cx, cy, w, h, angle) values; smoke_comp.sh gates on this file with tolerance."
    echo "# Format: class,file,found,cx,cy,w,h,angle,quality,method"
    for subdir in "$CORPUS_ROOT"/*/; do
        [ -d "$subdir" ] || continue
        class=$(basename "$subdir")
        # Component-classes only: fid corpus uses a different detector + smoke path.
        case "$class" in
            fid*|fiducial*) continue ;;
        esac
        # mvision-tune emits: file,found,cx,cy,w,h,angle,quality,method
        # Strip the header + path prefix, prepend the class name, drop the .png frames
        # subdir reference. Sort within class so the file is deterministic.
        "$TUNE" --corpus "$subdir" --thr 50 2>/dev/null \
            | awk -F, -v cls="$class" '
                NR == 1 { next }                  # skip header
                /^# / { next }                    # skip any stray comment
                $2 == "READ_ERROR" { next }       # skip unreadable rows
                {
                    n = split($1, p, "/")
                    file = p[n]
                    printf "%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n",
                        cls, file, $2, $3, $4, $5, $6, $7, $8, $9
                }' \
            | sort
    done
} > "$tmp"

mv "$tmp" "$OUT"
echo "wrote $OUT" >&2
cat "$OUT"
